short-language:
  english: en
  englisch: en
  german: de
  deutsch: de
available-languages:
  - de
  - en
default-language: en
replace-languages:
  at: de
  ch: de
save-user-language: true
commands:
- lang
- language
- sprache
prefix-for-time: true